language:
  - python
python:
  - "3.6"

before_install:
  - gem install bundler

install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install pytest
  - pip install coverage
  - pip install coveralls


services:
    - postgresql

addons:
    postgresql: '9.6'

before_script:
  - export FLASK_APP='run.py'
  - psql -c 'create database authentication;' -U postgres
  - export DB_URL='postgresql://postgres@localhost:5432/authentication'
  - flask create

script:
  - pytest --cov=app --cov-report=term-missing

after_success:
  - coveralls
  - codecov
